### ISSUE TITLE
log of activities from use of EvilWinRm

### ISSUE THREAD

**Issue by 1m0g** [OscarAkaElvis/OscarAkaElvis#1]
When an instance of EvilWinRm is loaded in memory, do the actions of it register to a log since it is utiziling the WinRm service for connection routing and management? If so, what directory might these logs exist under?

**Comment by OscarAkaElvis** [comment]
Evil-WinRM has no logging feature. Anyway, you can check WinRM logs on remote machine as normal. You can check if that logs are enabled `Get-WinEvent -ListLog *winrm*`. Anyway, if you need to contact us, do it by private msg on twitter.
